### ISSUE TITLE
Unexpected token "export" while installing this module

### ISSUE THREAD

**Issue by ChaitanyaKaranam** [elgs/ip6#4]
The latest commit for ES6 support is not backward compatible. This is breaking while using it with ``require``

**Comment by elgs** [comment]
Thanks for finding it. Do you think there's a way they can be together, or they have to be separated?

**Comment by elgs** [comment]
I fixed it by removing the `exprt`s and added a separate ip6-es.js for ES6 support. Who TF got the mjs nonsense idea, how stupid!

I am sorry for the problem.

**Comment by ChaitanyaKaranam** [comment]
> I fixed it by removing the `exprt`s and added a separate ip6-es.js for ES6 support. Who TF got the mjs nonsense idea, how stupid!
> 
> I am sorry for the problem.

Awesome! Thanks for the quick fix. I will give it a try.

**Comment by ChaitanyaKaranam** [comment]
> Thanks for finding it. Do you think there's a way they can be together, or they have to be separated?

@elgs We can use webpack and target it to [UMD](https://github.com/umdjs/umd). This will in both client and server. Axios does this. 

Let me know if you are accepting any PR's, I can give it a shot.

**Comment by elgs** [comment]
@ChaitanyaKaranam I do accept PR. Thank you. But I try to avoid any unnecessary dependencies. I think it's overkill to use Webpack for my tiny little one file project. Thank you for you advice though.
