### ISSUE TITLE
Bad npm publish?

### ISSUE THREAD

**Issue by EricMCornelius** [elgs/ip6#5]
```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/ubuntu/***/node_modules/ip6/ip6-bin.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/ubuntu/cyql-parse/node_modules/ip6/ip6-bin.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Looks like the latest npm publish is missing ip6-bin.js - which is causing installation failures for a variety of projects dependent on range_check.

**Comment by elgs** [comment]
Thank you so much! It's fixed.

**Comment by MewingPlane** [comment]
![image](https://user-images.githubusercontent.com/47350880/100218208-1b174900-2f1d-11eb-85a1-76b47f9cc3e2.png)
This is still broken

**Comment by elgs** [comment]
Can you please show me the line with ip6 in the dependencies or devDependencies section in your package.json file?

**Comment by MewingPlane** [comment]
`{
  "name": "resources",
  "version": "2019.2.0",
  "description": "Shared nodejs resources and modules",
  "main": "run.js",
  "author": "Sintrex",
  "license": "UNLICENSED",
  "dependencies": {
    "@elastic/elasticsearch": "^7.5.0",
    "async": "^2.5.0",
    "deep-object-diff": "^1.1.0",
    "elasticsearch": "^16.2.0",
    "eslint": "^4.12.1",
    "glob": "^7.1.4",
    "gulp": "^4.0.2",
    "influx": "^5.4.0",
    "int64_t": "^0.10.1",
    "ip": "^1.1.3",
    "ip6": "^0.1.8",
    "lodash": "^4.17.11",
    "minimist": "^1.2.0",
    "moment": "^2.24.0",
    "mysql": "^2.17.1",
    "net-snmp": "^2.5.3",
    "parse-duration": "^0.1.1",
    "promise.allsettled": "^1.0.2",
    "q": "^1.4.1",
    "request": "^2.83.0",
    "sinon": "^7.3.2",
    "sinon-chai": "^3.3.0",
    "winston": "^3.2.1",
    "winston-syslog": "^2.2.1",
    "zeromq": "^5.2.0"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.2",
    "chai": "^4.2.0",
    "gulp-eslint": "^6.0.0",
    "gulp-nodemon": "^2.4.2",
    "gulp-util": "^3.0.8",
    "mocha": "^6.1.4",
    "nyc": "^14.1.1"
  }
}
`


so this is my package.json file contents, I created a new project from scratch, added this to my pack file and did an npm install, I still get the error, this is on Ubuntu 18.0.4

the only way around this is to roll back an set to version 0.1.8

**Comment by elgs** [comment]
Or you can change it to ^0.2.0. I am so sorry 0.1.9 is a bad version due to my fault.
