### ISSUE TITLE
Does not invalidate if >4 hex digits is provided within colon set

### ISSUE THREAD

**Issue by DavidLui** [elgs/ip6#6]
ipv6.normalize('012345:6800:4003:808::200e'));
    Received: "012345:6800:4003:0808:0000:0000:0000:200e"

**Comment by elgs** [comment]
@DavidLui, this should have been fixed in v0.2.3.

**Comment by DavidLui** [comment]
Hi elgs,

Reopening to follow up for v.0.2.3, my webpack loader no longer works because of the '?' symbol

![image](https://user-images.githubusercontent.com/5111021/113013208-85e5c480-9149-11eb-8588-090caf0decae.png)


Can you update ip6 to use the simple check instead?

      if (match?.[0] !== n) {
         throw new Error('Invalid address: ' + a);
      }

to

      if (match && match[0] !== n) {
         throw new Error('Invalid address: ' + a);
      }


Much appreciated.

https://github.com/elgs/ip6/compare/0.2.2...0.2.3#diff-440434714e481098291ea2deb19f62788d2e81e12b39dedabcba6982ead1b827R120

https://github.com/elgs/ip6/compare/0.2.2...0.2.3#diff-ce79cd42290de2bf5e7b2c69b0a45a6466dfb4513f602402eb383054443a59f2R120

**Comment by elgs** [comment]
Fixed in 0.2.6. Can you please try again? Thanks.

**Comment by DavidLui** [comment]
Awesome! Appreciate the quick reply. Working now.
